Controllers/RegisteredInviteeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BCRM.CheckInEvent.Models;
using BCRM.CheckInEvent.Common;
using BCRM.CheckInEvent.DAL;
using Libs;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using BCRM.CheckInEvent.SendSMSGAPIT;
using System.Configuration;
using Newtonsoft.Json;
using System.Data;
using System.Text;

namespace BCRM.CheckInEvent.Controllers
{
    public class RegisteredInviteeController : BaseController
    {
        #region methods
        [FilterAuthorize]
        public ActionResult Index()
        {
            // authentication
            if (!UserContext.HasPermisson(Permission.Admin) 
                && !UserContext.HasPermisson(Permission.InviteeManager)
                && !UserContext.HasPermisson(Permission.Manager))
            {
                return View("~/Views/Common/NotPermitted.cshtml");
            }
            var defaultEvent = CommonMethod.GetDefaultEvent();
            ViewBag.CurrentUser = UserContext;
            ViewBag.DefaultEvent = defaultEvent;
            var userDL = new UserDL();
            ViewBag.LstAssignTo = userDL.GetByRole(Permission.InviteeManager.GetHashCode()).OrderBy(o=>o.UserName).ToList();
            // Lấy danh sách các sự kiện
            var inviteInventDL = new InviteEventDL();
            var eventDL = new EventDL();
            var lstAllEvents = eventDL.GetAllInWebCheckIn().FindAll(o => o.IsEnable == true).OrderByDescending(o => o.CreatedDate).ToList();
            foreach (var eventInfo in lstAllEvents)
            {
                eventInfo.IsInWebCheckIn = true;
            }
            return View(lstAllEvents);
        }
        [FilterAuthorize]
        public ActionResult Create()
        {
            // authentication
            if (!UserContext.HasPermisson(Permission.Admin) && !UserContext.HasPermisson(Permission.InviteeManager))
            {
                return View("~/Views/Common/NotPermitted.cshtml");
            }
            var eventDL = new EventDL();
            var defaultEvent = CommonMethod.GetDefaultEvent();
            if (defaultEvent == null)
            {
                defaultEvent = new EventModel()
                {
                    Id = 0
                };
            }
            var lstAllEventWebCheckin = eventDL.GetAllInWebCheckIn().FindAll(o => o.IsEnable == true).OrderByDescending(o => o.CreatedDate).ToList();
            if (defaultEvent.IsInWebCheckIn)
            {
                if (lstAllEventWebCheckin.Find(o => o.Id == defaultEvent.Id) != null)
                {
                    ViewBag.DefaultEvent = defaultEvent;
                }
                else
                {
                    ViewBag.DefaultEvent = new EventModel()
                    {
                        Id = 0,
                        IsInWebCheckIn = true
                    };
                }

            }
            ViewBag.LstEvent = lstAllEventWebCheckin.OrderByDescending(o => o.CreatedDate).ToList();

            var onlineInviteeForCreate = new OnlineInviteeForCreateModel();
            
            ViewBag.CurrentUser = UserContext;

            return View(onlineInviteeForCreate);
        }
        [FilterAuthorize]
        public JsonResult CreateAction(OnlineInviteeModel model)
        {
            var response = new Response();
            var inviteEventDL = new InviteEventDL();
            #region Kiểm tra quyền và validate dữ liệu đầu vào
            if (!UserContext.HasPermisson(Permission.InviteeManager) && !UserContext.HasPermisson(Permission.Admin))
            {
                response.Code = SystemCode.NotPermitted;
                response.Message = "Bạn không có quyền thực thi chức năng này !";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            //validate thông tin
            // Tên khách hàng bắt buộc nhập
            // Số điện thoại bắt buộc nhập
            // Email bắt buộc nhập
            if (string.IsNullOrEmpty(model.CustomerName) || string.IsNullOrEmpty(model.CustomerPhone) || string.IsNullOrEmpty(model.CustomerEmail))
            {
                response.Code = SystemCode.NotValid;
                response.Message = "Dữ liệu không hợp lệ";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            // Kiểm tra số điện thoại
            
            if (inviteEventDL.WebCheckIn_CheckPhoneExist(0, model.EventId, model.CustomerPhone))
            {
                response.Code = SystemCode.NotValid;
                response.Message = "Số điện thoại này đã được sử dụng";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            // Kiểm tra địa chỉ email
            if (inviteEventDL.WebCheckIn_CheckEmailExist(0, model.EventId, model.CustomerEmail))
            {
                response.Code = SystemCode.NotValid;
                response.Message = "Email này đã được sử dụng !";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            var msg = "";
            if (!ValidateConfirmAttend(model, ref msg))
            {
                response.Code = SystemCode.NotValid;
                response.Message = msg;
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            #endregion
            // Lấy thông tin sự kiện
            var eventInfo = (new EventDL()).GetByIdInWebCheckIn(model.EventId);
            // Sinh mã vé cho khách mời ,Lặp tối đa 100 lần nếu như đã tồn tại mã vé này rồi
            for (var index = 0; index < 100; index++)
            {
                model.Code = string.Format("{0}{1}", eventInfo.EventCode, CommonMethod.GenerateCode());
                // Kiểm tra xem mã vé này đã tồn tại chưa
                if (!inviteEventDL.WebCheckin_IsExistCode(eventInfo.Id, model.Code))
                {
                    break;
                }
            }
            // Lấy thông tin người tạo
            model.CreatedBy = UserContext.UserName;
            // Lấy thông tin ngày đăng kí
            model.RegisteredDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day, 0, 0, 0);
            // Kiểm tra phiên tham dự của khách mời có chọn tất cả không ,
            // nếu có thì loại bỏ các phiên riêng lẻ được chọn khác
            if (!string.IsNullOrEmpty(model.Sessions))
            {
                var lstSessions = model.Sessions.Split(',').ToList();
                if (lstSessions.Contains("0"))
                {
                    model.Sessions = "0";
                }
            }
            // Lưu thông tin khách mời được tạo mới
            var id = inviteEventDL.InsertOnlineInvitee(model);
            // Lưu lại lịch sử thêm mới khách mời
            var inviteEventHistoryDL = new InviteEventHistoryDL();
            inviteEventHistoryDL.Insert(new InviteEventHistoryModel()
            {
                Action= "Tạo mới",
                OldValue = "",
                NewValue ="",
                UpdatedBy = UserContext.UserName,
                InviteEventId = id
            });

            response.Code = SystemCode.Success;
            response.Message = "Bạn đã thêm thông tin thành công !";
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [FilterAuthorize]
        public ActionResult Search(FilterForOnlineRegisterSearchModel model)
        {
            if (!UserContext.HasPermisson(Permission.Admin) && 
                !UserContext.HasPermisson(Permission.InviteeManager) &&
                !UserContext.HasPermisson(Permission.Manager))
            {
                return View("~/Views/Common/NotPermitted.cshtml");
            }
            if (!string.IsNullOrEmpty(model.TextSearch))
            {
                model.TextSearch = model.TextSearch.Trim();
            }
            else
            {
                model.TextSearch = "";
            }
            if (string.IsNullOrEmpty(model.AssignTo))
            {
                model.AssignTo = "";
            }
            if (!string.IsNullOrEmpty(model.IntroduceUser))
            {
                model.IntroduceUser = model.IntroduceUser.Trim();
            }
            else
            {
                model.IntroduceUser = "";
            }

            if (model.StartDate == null || model.StartDate == DateTime.MinValue)
            {
                model.StartDate = new DateTime(2000, 1, 1, 0, 0, 0);
            }
            if (model.EndDate == null || model.EndDate == DateTime.MinValue)
            {
                model.EndDate = new DateTime(9999, 1, 1, 0, 0, 0);
            }
            else
            {
                model.EndDate = model.EndDate.Value.AddHours(23).AddMinutes(59).AddSeconds(59);
            }

            var inviteEventDL = new InviteEventDL();
            var result = new FilterForOnlineRegisterSearchModel();
            var lstSearchResult = new List<OnlineInviteeForSearchModel>();
            // Tìm kiếm theo mã số khách mời
            if (model.InviteeCode > 0)
            {
                var info = inviteEventDL.WebCheckIn_GetRegisteredInviteeById(model.InviteeCode);
                if (info != null)
                {
                    lstSearchResult.Add(info);
                }
            }
            // Tìm kiếm theo mã vé
            else if (!string.IsNullOrEmpty(model.Code))
            {
                var iCode = 0;
                if (int.TryParse(model.Code, out iCode))
                {
                    var eventDL = new EventDL();
                    var eventInfo = eventDL.GetByIdInWebCheckIn(model.EventId);
                    if (eventInfo != null)
                    {
                        model.Code = eventInfo.EventCode + model.Code;
                    }
                }

Views/RegisteredInvitee/AssignTo.cshtml
@using BCRM.CheckInEvent.Models
@model List<UserModel>
<div id="frmAssignTo" style="width: 420px; display: block; top: 25%; left: 40%; overflow-x: hidden; overflow-y: hidden !important;outline:none;"  class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialogSuccessLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="height: 100%;padding: 0px;border: none;">
        <div class="modal-content" style="border-radius:0px;width: 420px;">
            <div class="modal-header" style="color: #fff;background-color: #428bca;border-color: #d43f3a;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="dialogSuccessLabel">Giao khách mời cho nhân viên</h4>
            </div>
            <div class="modal-body" >
                <div class="row" style="color:Red;" id="wrapShowErrAssignTo">
                    <div class="form-group " >
                        <span>Bạn phải nhập thông tin </span>    
                    </div>
                </div>
                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="control-label">Lựa chọn nhân viên để giao <span style="color:Red;">*</span></label>
                        <div class="input-group">
                            <select id="selAssignTo" class="chzn-select form-control select" style="width:300px;">
                                @foreach (var assignTo in Model)
                                {
                                    <option value="@assignTo.UserName">@assignTo.UserName</option>
                                }
                            </select>
                        </div>
                        <div class="show-message"></div> 
                    </div>
                </div>
                <div class="actions col-md-12" style="padding-bottom:5px;padding-top:20px;border-top:1px solid #ddd;margin-top:10px;">
                    <button id="btnSaveAssignTo" type="button" class="btn btn-success"><i class="icon-save"></i>&nbsp;GIAO KHÁCH MỜI</button>
                    <button id="btnCancelAssignTo" type="button" class="btn btn-primary"  data-dismiss="modal"><i class="icon-remove"></i>&nbsp;ĐÓNG</button>
                </div> 
            </div>
        </div>
    </div>
</div>

Views/RegisteredInvitee/AssignToSale.cshtml
@using BCRM.CheckInEvent.Models
@model List<CustomerModel>
@{
    Layout = null;
    var lstSale = (List<string>)ViewBag.LstSale;
    var chosenSaler = ViewBag.ChosenSaler;
}
@if (Model.Count > 0)
{
     <div class="row">
        <div class="form-group col-md-12" >
            <label class="control-label" for="ddlAssignToSale">Khách hàng đang được chăm sóc bởi :</label>
            <div class="input-group">
                <span>@Model[0].AssignTo </span>
            </div>
        </div>
        @if (!string.IsNullOrEmpty(chosenSaler))
        {
            <div class="form-group col-md-12" >
                <label class="control-label" for="ddlAssignToSale">Khách hàng đang được giao cho :</label>
                <div class="input-group">
                    <span>@chosenSaler </span>
                </div>
            </div>     
        }
        
    </div>
    <hr />
}
else
{
    <div class="row">
        <div class="form-group col-md-12" >
            <div class="alert alert-warning">
              <strong>Cảnh báo!</strong> Khách hàng chưa có thông tin trên BCRM , bạn không thể thực hiện chức năng này .
            </div>
        </div>
    </div>
    <hr /> 
}
@if (Model.Count > 0)
{
<div class="row">
    
        <div class="form-group col-md-12" >
            <label class="control-label" for="ddlAssignToSale">Giao cho<span style="color:Red;">*</span></label>
            <div class="input-group">
        
                 <select name="ddlAssignToSale" class="chzn-select form-control select" style="width:350px;" placeholder="Lựa chọn phòng ban" >
                    @if (!string.IsNullOrEmpty(chosenSaler))
                    {
                        foreach (var item in lstSale)
                        {
                            if (chosenSaler == item)
                            {
                                <option selected value="@item"> @item </option>     
                            }
                            else
                            {
                                <option value="@item"> @item </option>     
                            }

                        }
                    }
                    else if (Model.Count > 0)
                    {
                        foreach (var item in lstSale)
                        {
                            if (Model[0].AssignTo == item)
                            {
                                <option selected value="@item"> @item </option>     
                            }
                            else
                            {
                                <option value="@item"> @item </option>     
                            }

                        }
                    }
                    else
                    {
                        foreach (var item in lstSale)
                        {
                            <option value="@item"> @item </option>     
                        }
                    }
                </select>
        
            </div>
            <div class="show-message"></div>
        </div>

</div>
<hr />
}
<div class="row col-md-12">
    @if (Model.Count > 0)
    {
        <button name="btnSaveAssignToSale" iid="@((int)ViewBag.InviteeId)" type="button" class="btn btn-primary"><i class="icon-save"></i>&nbsp;Gán cho Sale</button>     
    }
    <button name="btnCloseAssignToSale" type="button" class="btn btn-primary"><i class="icon-close"></i>&nbsp;Đóng</button>
</div>

Views/RegisteredInvitee/EditHistoryPartial.cshtml
@using BCRM.CheckInEvent.Common
@model List<BCRM.CheckInEvent.Models.InviteEventHistoryModel>
@{
    var count = 0;
    }
<a id="toogleHistory" href="javascript:void(0);" style="font-size: 24px;color: #000;width: 100%;background: rgb(221, 221, 221);cursor: pointer;text-decoration: none;padding-left:5px;"  title="Hiển thị danh sách lịch sử thao tác với khách mời">
    <span>+</span> Lịch sử thay đổi khách mời
</a>
<table id="tblHistory" class="table-striped table-bordered hide" style="width: 100%;margin-top:25px;">
    <tr>    
        <th>#</th>
        <th>Thao tác</th>
        <th>Trước thay đổi</th>
        <th>Sau thay đổi</th>
        <th>Ghi chú</th>
        <th>Người xử lý</th>
        <th>Ngày xử lý</th>
    </tr>
    @foreach (var item in Model)
    {
        count++;
        <tr>
            <td>@count</td>
            <td><span class="label label-info">@item.Action</span> </td>
            <td>@item.OldValue</td>
            <td>@item.NewValue</td>
            <td>@item.Note</td>
            <td>@item.UpdatedBy</td>
            <td>@item.UpdatedDate.ToString("dd/MM/yyyy HH:mm:ss")</td>
        </tr>
        @*<tr>
            <td> 
                @foreach (var changeItem in item.LstOtherChangeItem)
                {
                    <a href="javascript:void(0);" >@(changeItem.FieldDisplay) :</a>  <span> @(string.IsNullOrEmpty(changeItem.OldValue) ? "Không có" : changeItem.OldValue)     </span><b><i class="icon-arrow-right"></i></b> <span style="color:red;">@(string.IsNullOrEmpty(changeItem.NewValue) ? "Không có" : changeItem.NewValue)</span> <br />
                }
            </td>
            <td>
                <div class="col-md-12" style="text-align: center;">
                    @if (item.Status == 1)
                    {
                        <span class="label label-info">Tạo mới</span>
                    }
                    else if (item.Status == 2)
                    {
                        <span class="label label-info">Sửa</span> 
                    }
                    else if (item.Status == 3)
                    {
                        <span class="label label-info">Duyệt</span> 
                    }
                    else if (item.Status == 4)
                    {
                        <span class="label label-info">Hủy duyệt</span> 
                    }
                    else if (item.Status == 5)
                    {
                        <span class="label label-info">Xóa</span> 
                    }
                </div>
            </td>
            <td>
                <div class="col-md-12" style="text-align: center;">
                    <span>@item.UpdatedBy</span> 
                </div>
            </td>
            <td>@item.UpdatedDate.ToString("dd/MM/yyyy HH:mm:ss")</td>     
        </tr>*@
    }
</table>

Views/RegisteredInvitee/Index.cshtml
@using BCRM.CheckInEvent.Models
@model List<EventModel>
@{
    Layout = "~/Views/Shared/_ContentLayout.cshtml";
    var lstAssignTo = (List<UserModel>)ViewBag.LstAssignTo;
    var currentUsser = (UserModel)ViewBag.CurrentUser;
    var defaultEvent = ViewBag.DefaultEvent == null ? new EventModel() { Id = 0 } : (EventModel)ViewBag.DefaultEvent;
}
<h1 style="padding-left: 15px;">
    Quản lý khách mời</h1>
<style type="text/css">
    input.phone-search::-webkit-outer-spin-button,
    input.phone-search::-webkit-inner-spin-button 
    {
        -webkit-appearance: none;
        margin: 0;
    }
    input.phone-search {
        -moz-appearance:textfield;
    }
</style>
@using (Html.BeginForm("ExportExcel", "RegisteredInvitee", FormMethod.Post, new { id = "registeredInviteeForm",target="_blank" }))
{
    <div class="panel panel-search"  id="frmSearchRegisteredInvitee">
        <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Tìm kiếm thông tin khách mời</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="input-group">
                        <textarea name="TextSearch" rows="5" cols="5" class="form-control" id="txtSearchText" placeholder="Tìm kiếm theo họ tên, email,điện thoại ... "></textarea>
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-4">
                            <div class="input-group">
                                <select name="EventId" id="selEvent" class="form-control" title="Danh sách các sự kiện diễn ra">
                                    @foreach (var e in Model)
                                    {
                                        if (e.Id == defaultEvent.Id && e.IsInWebCheckIn == defaultEvent.IsInWebCheckIn)
                                        {
                                            <option selected="selected" value="@(e.Id)">@e.Name</option>                                               
                                        }
                                        else
                                        {
                                            <option value="@(e.Id)">@e.Name</option> 
                                        }
                                    }
                                </select> 
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <select id="dllSessions"  class="form-control">
                                    <option value="0">--Chọn phiên --</option>
                                </select>
                            </div>
                        </div>
                               
                        <div class="col-md-3">
                            <div class="input-group">
                                <select name="InviteeResponseStatus" id="selIsCheckIn" class="form-control" title="Thông tin khách đã check in hay chưa">
                                    <option value="">--Tất cả trạng thái--</option>
                                    <option value="1">Xác nhận lần 1</option>
                                    <option value="2">Xác nhận lần 2</option>
                                    <option value="3">Chưa gọi</option>
                                    <option value="4">Gọi lại sau</option>
                                    <option value="5">Không nghe máy</option>
                                    <option value="6">Đã gọi</option>
                                    <option value="7">Số máy sai</option>
                                    <option value="8">Đang xem xét</option>
                                    <option value="9">Không tham gia</option>
                                    <option value="10">Đã gửi vé </option>
                                    <option value="11">Gửi lại vé </option>
                                    <option value="12">Không mời </option>
                                    <option value="13">Trưởng phòng duyệt </option>
                                </select>
                            </div>
                        </div>  
                        <div class="col-md-2">
                            <div class="input-group">
                                <select name="SourceId" id="selCustomerType" class="form-control" title="Nguồn khách mời">
                                    <option value="0">- Nguồn khách mời -</option>
                                    <option value="1">BCRM</option>
                                    <option value="2">Landingpage</option>
                                </select>
                            </div>
                        </div>
                        
                    </div>
                    <div class="row" style="margin-top:3px;">
                        <div class="col-md-2">
                            <div class="input-group">
                                <input type="number" name="InviteeCode" id="txtInviteeCode" placeholder="- Mã số -" class="form-control phone-search" />
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="input-group">
                                <input type="text" name="Code" id="txtCode" placeholder="- Mã vé -" class="form-control" />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group date">
                                <input type="text" id="txtStartRegisterDate" value="" placeholder="-- KH bắt đầu đ/kí từ--" class="form-control date">
                            </div>   
                        </div>
                        <div class="col-md-3">
                            <div class="input-group date">
                                <input type="text" id="txtEndRegisterDate" value="" placeholder="--  Đến hết ngày đ/kí--" class="form-control date">
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="input-group">
                                <select name="AssignTo" id="selAssignTo" class="form-control" title="Giao khách hàng cho">
                                    <option value="">-Giao cho-</option>
                                    @foreach (var assignTo in lstAssignTo)
	                                {
		                                <option value="@assignTo.UserName">@assignTo.UserName</option>
	                                }
                                </select>    
                            </div>
                        </div> 
                    </div>    
                    <div class="row" style="margin-top:3px;">
                        <div class="col-md-4">
                            <div class="input-group">
                                <input type="text" name="IntroduceUser" id="txtIntroduceUser" placeholder="- Nhân viên mời -" class="form-control " />
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <select name="FilterAssignTo" id="selFilterAssignTo" class="form-control select" title="Lựa chọn thông tin khách hàng được giao">
                                    <option value="0">- Lựa chọn thông tin khách hàng được giao -</option>
                                    <option value="1">Chưa giao cho ai </option>
                                    <option value="2">Chưa giao cho Sale</option>
                                    <option value="3">Chưa giao cho CSKH</option>
                                    <option value="4">Đã giao cho Sale</option>
                                    <option value="5">Đã giao cho CSKH</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div style="width: 100%;margin-top:3px; margin-bottom: 3px;">
                <button id="btnSearch" class="btn btn-success" type="button">
                    <i class="icon-search"></i>
                    &nbsp;Tìm kiếm
                </button>
                @if (currentUsser.HasPermisson(BCRM.CheckInEvent.Common.Permission.InviteeManager) ||
                    currentUsser.HasPermisson(BCRM.CheckInEvent.Common.Permission.Admin))
                {
                    <button id="btnExport" class="btn btn-success" type="button">
                        <i class="icon-refresh"></i>&nbsp;Xuất Excel
                    </button>         
                }
                <button id="btnAddInvitee" class="btn btn-success" type="button">
                    <i class="icon-plus"></i>
                    &nbsp;Thêm Khách mời
                </button>
                <input type="hidden" id="hdfSearchStartDate" name="StartDate" />
                <input type="hidden" id="hdfSearchEndDate" name="EndDate" />
            </div>
        </div>
    </div>
}

<div class="panel panel-result" id="SearchRegisteredInvitee">
    <div class="panel-heading">
        <i class="icon-reorder"></i> &nbsp; Danh sách khách mời
    </div>
    <div class="panel-body"></div>
</div>

<div class="panel panel-action hide" id="wrapAssignToSale">
    <div class="panel-heading">
        <i class="icon-edit"></i> &nbsp; Giao cho Sale
    </div> 
    <div class="panel-body">
    </div>
</div>

<div class="panel panel-action hide" id="AddRegisteredInvitee">
    <div class="panel-heading">
        <i class="icon-edit"></i> &nbsp; Thêm / sửa khách mời
    </div> 
    <div class="panel-body">
        
    </div>
</div>
<div id="wrapAssignTo" class="hide">
    @Html.Partial("~/Views/RegisteredInvitee/AssignTo.cshtml", lstAssignTo)    
</div>
<script type="text/javascript">
    registered_invitee_index.init();
</script>