Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Libs;
using BCRM.CheckInEvent.Models;
using BCRM.CheckInEvent.Common;
using BCRM.CheckInEvent.DAL;

namespace BCRM.CheckInEvent.Controllers
{
    public class EventController : BaseController
    {
        [FilterAuthorize]
        public ActionResult Index()
        {
            var model = new EventIndexSearchModel();
            model.LstGroup = (new BCRMGroupsDL()).GetAllGroups().FindAll(o => o.ParentId == 0).OrderBy(g => g.Order).ToList();
            return View(model);
        }
        [FilterAuthorize]
        public ActionResult Search(EventIndexSearchModel model)
        {
            // Người dùng phải có quyền quản lý mới thực hiện được chức năng này
            if (!UserContext.HasPermisson(Permission.Admin) && !UserContext.HasPermisson(Permission.Manager))
            {
                return View("~/Views/Common/NotPermitted.cshtml");
            }
            if (!string.IsNullOrEmpty(model.FilterTextSearch))
            {
                model.FilterTextSearch = model.FilterTextSearch.Trim();
            }
            var eventDL = new EventDL();
            
            // Lấy thông tin event trên web checkin theo điều kiện tìm kiếm
            var lstEvent = eventDL.GetListInWebCheckIn(model.FilterTextSearch,model.DeployEventId ,model.StartDate,model.EndDate);
            foreach (var item in lstEvent)
            {
                item.IsInWebCheckIn = true;
            }
            var lstSearchResult = new List<EventModel>();
            //lstSearchResult.AddRange(lstEventBCRMs);
            lstSearchResult.AddRange(lstEvent);
            // Sắp xếp theo ngày bắt đầu diễn ra sự kiện
            lstSearchResult = lstSearchResult.OrderByDescending(o => o.StartDate).ToList();
            // Lấy ra thông tin sự kiện được đặt mặc định
            var setDefaultEventDL = new SetDefaultEventDL();
            var setDefaultInfo = setDefaultEventDL.GetLastest();
            foreach (var item in lstSearchResult)
            {
                if (setDefaultInfo != null)
                {
                    if (item.Id == setDefaultInfo.EventId && item.IsInWebCheckIn == setDefaultInfo.IsInWebCheckin && !setDefaultInfo.IsCancel)
                    {
                        item.IsDefaultEvent = true;
                    }
                    else
                    {
                        item.IsDefaultEvent = false;
                    }
                }
                else
                {
                    item.IsDefaultEvent = false;
                }
            }
            lstSearchResult = lstSearchResult.OrderByDescending(o => o.CreatedDate).ToList();
            var lstReturn = lstSearchResult.Skip(model.PageSize * (model.PageIndex - 1))
                                                       .Take(model.PageSize).ToList();
            model.LstEvent = lstReturn;
            model.TotalRecord = lstSearchResult.Count;
            var pager = new PagerModel { CurrentPage = model.PageIndex, PageSize = model.PageSize, TotalItem = model.TotalRecord };
            ViewBag.Pager = pager;
            return View(model);
        }
        [FilterAuthorize]
        public ActionResult Create()
        {
            var groupLayer = new BCRMGroupsDL();
            var model = new EventModelForCreate();
            var allGroups = groupLayer.GetAllGroups().FindAll(o => o.ParentId == 0).OrderBy(g => g.Order).ToList();
            model.LstGroup = allGroups;
            return View(model);
        }
        [FilterAuthorize]
        public JsonResult CreateAction(EventModelForCreate model)
        {
            if (model.LstSession == null)
            {
                model.LstSession = new List<SessionForSaveModel>();
            }
            var response = new Response();
            // Kiểm tra thông tin phân quyền
            // Người dùng phải có quyền Manager hoặc Admin thì mới được thực thi chức năng này
            if ( !UserContext.HasPermisson(Permission.Manager) && !UserContext.HasPermisson(Permission.Admin))
            {
                response.Code = SystemCode.NotPermitted;
                response.Message = "Bạn không có quyền thực thi chức năng này !";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            // Validate lại dữ liệu
            if (model.StartDate == DateTime.MinValue || model.EndDate == DateTime.MinValue  )
            {
                response.Code = SystemCode.NotValid;
                response.Message = "Dữ liệu người dùng nhập vào không hợp lệ";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            // Ngày bắt đầu phải nhỏ hơn hoặc bằng ngày kết thúc
            if (model.StartDate > model.EndDate)
            {
                response.Code = SystemCode.NotValid;
                response.Message = "Ngày bắt đầu phải nhỏ hơn hoặc bằng ngày kết thúc";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            // Lấy thông tin người tạo
            model.CreatedBy = UserContext.UserName;

            if (model.IsBcrmUse)
            {
                if (model.RevenueStartDate != null)
                {
                    model.RevenueStartDate = model.RevenueStartDate.Value.Date;
                }
                if (model.RevenueEndDate != null)
                {
                    model.RevenueEndDate = model.RevenueEndDate.Value.Date.AddDays(1).AddSeconds(-1);
                }
                var arrDeploy = model.Deploy.Split(',');
                if (arrDeploy.Contains("0"))
                {
                    model.Deploy = "0";
                }
            }
            else
            {
                model.RevenueStartDate = null;
                model.RevenueEndDate = null;
                model.Deploy = "";
                model.IsAllowAttach = null;
                model.RevenueCalculation = 0;
            }
            // Thêm mới sự kiện
            var eventDL = new EventDL();
            // Kiểm tra mã sự kiện đã tồn tại chưa
            var eventCodeInfo = eventDL.GetByEventCodeInWebCheckIn(model.Id, model.EventCode);
            if (eventCodeInfo != null)
            {
                response.Code = SystemCode.ErrorExist;
                response.Message = "Mã sự kiện đã tồn tại rồi";
                return Json(response, JsonRequestBehavior.AllowGet);
            }
            var eventId = eventDL.CreateInWebCheckIn(model);

            var sessionDL = new SessionDL();
            if (model.LstSession.Count > 0)
            {
                foreach (var sessionItem in model.LstSession)
                {
                    sessionItem.EventId = eventId;
                    sessionItem.StartDate = sessionItem.StartDate.AddHours(sessionItem.StartTime.Hours).AddMinutes(sessionItem.StartTime.Minutes);
                    sessionItem.EndDate = sessionItem.EndDate.AddHours(sessionItem.EndTime.Hours).AddMinutes(sessionItem.EndTime.Minutes);
                    sessionDL.Create(new SessionModel() { 
                        Name = sessionItem.Name,
                        StartDate = sessionItem.StartDate,
                        EndDate = sessionItem.EndDate,
                        Description = sessionItem.Description,
                        EventId = sessionItem.EventId
                    });
                }
            }

            // Nếu sự kiện được chọn là sự kiện mặc định
            if (model.IsDefaultEvent)
            {
                // Thêm thông tin sự kiện mặc định
                var setDefaultEventDL = new SetDefaultEventDL();
                setDefaultEventDL.Create(new SetDefaultEventModel() { 
                        EventId = eventId,
                        CreatedBy = UserContext.UserName,
                        IsInWebCheckin = true
                });
            }
            // Gửi thông báo thành công
            response.Code = SystemCode.Success;
            response.Message = "Bạn đã thêm mới sự kiện thành công";
            
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        [FilterAuthorize]
        public ActionResult Edit(int id)
        {
            // Kiểm tra người dùng có quyền manager / admin hay không
            if (!UserContext.HasPermisson(Permission.Admin) && !UserContext.HasPermisson(Permission.Manager))
            {
                return View("~/Views/Common/NotPermitted.cshtml");
            }
            // Lấy thông tin sự kiện
            var eventDL = new EventDL();
            var eventInfo = eventDL.GetByIdInWebCheckIn(id);
            var result = new EventModelForCreate() { 
                Id = eventInfo.Id,
                EventCode = eventInfo.EventCode,
                StartDate = eventInfo.StartDate,
                EndDate = eventInfo.EndDate,
                Deadline = eventInfo.Deadline,
                Deploy = eventInfo.Deploy,
                Description = eventInfo.Description,
                IsAllowAttach = eventInfo.IsAllowAttach,
                IsBcrmUse    = eventInfo.IsBcrmUse,
                IsDefaultEvent = eventInfo.IsDefaultEvent,
                IsEnable = eventInfo.IsEnable,
                Name = eventInfo.Name,
                SMSTitle = eventInfo.SMSTitle,
                RevenueCalculation = eventInfo.RevenueCalculation,
                RevenueStartDate = eventInfo.RevenueStartDate,
                RevenueEndDate = eventInfo.RevenueEndDate
            };
            if (eventInfo.IsBcrmUse)
            {
                result.LstDeployId = eventInfo.Deploy.Split(',').Select(o => int.Parse(o)).ToList();
            }

            // Kiểm tra xem sự kiện đang sửa có phải là sự kiện  mặc định
            var setDefaultEventDL = new SetDefaultEventDL();
            var setDefaultEvent = setDefaultEventDL.GetLastest();

            ViewBag.IsDefaultEvent = false;

Views/Event/Create.cshtml
@using BCRM.CheckInEvent.Models
@model EventModelForCreate
@{
    Layout = null;
}
<div id="frmAddNewEvent" class="col-md-12">
    <div class="row">
        <div class="form-group col-md-3">
            <label class="control-label" for="txtEventCode">Mã sự kiện <span style="color:Red;">*</span></label>
            <div class="input-group">
                <input  id="txtEventCode" type="text" class="form-control text-input" />    
            </div>
            <div class="show-message">
                
            </div>
        </div>
        <div class="form-group col-md-9">
            <label class="control-label" for="txtEvent">Sự kiện <span style="color:Red;">*</span></label>
            <div class="input-group">
                <input id="txtEvent" type="text" style="width:100%;" class="form-control text-input" />
            </div>
            <div class="show-message"></div>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-3">
            <label  class="control-label" for="txtStartTime">Ngày bắt đầu<span style="color:Red;">*</span></label>
            <div class='input-group date' >
                <input type='text' id='txtStartTime' class="form-control date" />
            </div>
            <div class="show-message">
            </div>
        </div>
        <div class="form-group col-md-3">
            <label  class="control-label" for="txtEndTime">Ngày kết thúc <span style="color:Red;">*</span></label>
            <div class='input-group date' >
                <input type='text' id='txtEndTime' class="form-control date" />
            </div>
            <div class="show-message">
            </div>
        </div>    
        <div class="col-md-6 ">
            <div class="row">
                <div class="form-group col-md-2" style="padding-right:0px;" >
                    <label  class="control-label" for="chkActive">Hoạt động </label>
                    <div class='input-group' >
                        <input type="checkbox" id="chkActive" class="checkbox" checked="checked" />
                    </div>
                    <div class="show-message">
                    </div>
                </div>
                <div class="form-group col-md-4" style="padding-right:0px;">
                    <label  class="control-label" for="chkDefaultEvent">Sự kiện mặc định </label>
                    <div class='input-group' >
                        <input type="checkbox" id="chkDefaultEvent" class="checkbox" />
                    </div>
                    <div class="show-message">
                    </div>
                </div>
                <div class="form-group col-md-4" style="padding-right:0px;">
                    <label  class="control-label" for="chkIsBcrmUse">Áp dụng cho BCRM </label>
                    <div class='input-group' >
                        <input type="checkbox" id="chkIsBcrmUse" class="checkbox" />
                    </div>
                </div>  
                
            </div>
        </div>
    </div>
    <div class="row" name="UsingInBCRM">
        <div class="form-group col-md-3">
            <label  class="control-label" for="txtDeadline">Ngày chốt sự kiện<span style="color:Red;">*</span></label>
            <div class='input-group date' >
                <input type='text' id='txtDeadline' class="form-control date" />
            </div>
            <div class="show-message"></div>
        </div>
        <div class="form-group col-md-3">
            <label class="control-label" for="txtRevenueStartDate">Ngày bắt đầu tính doanh thu<span style="color:Red;">*</span></label>
            <div class='input-group date' >
                <input type='text' id='txtRevenueStartDate' class="form-control date" />
            </div>
            <div class="show-message"></div>
        </div>
        <div class="form-group col-md-3">
            <label class="control-label" for="txtRevenueEndDate">Ngày kết thúc tính doanh thu<span style="color:Red;">*</span></label>
            <div class='input-group date' >
                <input type='text' id='txtRevenueEndDate' class="form-control date" />
            </div>
            <div class="show-message"></div>
        </div>
    </div>
    <div class="row" name="UsingInBCRM">
        <div class="form-group col-md-3">
            <label class="control-label" for="ddlRevenueCalculation">Cách tính doanh thu<span style="color:Red;">*</span></label>
            <div class='input-group' >
                <select id="ddlRevenueCalculation" class="form-control select">
                    <option value="1">Tính tổng</option>
                    <option value="2">Tính trung bình</option>
                </select>
            </div>
            <div class="show-message"></div>
        </div>
        <div class="form-group col-md-3">
            <label class="control-label" for="chkIsAllowAttach">Cho phép đính kèm </label>
            <div class='input-group' >
                <input type="checkbox" id="chkIsAllowAttach" checked="checked"  class="checkbox" />
            </div>
            <div class="show-message"></div>
        </div>
        <div class="form-group col-md-6" >
            <label class="control-label" for="ddlDeployEvent">Áp dụng cho<span style="color:Red;">*</span></label>
            <div class="input-group">
                <select id="ddlDeployEvent" multiple class="chzn-select form-control select" style="width:350px;" placeholder="Lựa chọn phòng ban" >
                    <option value="0">Chọn tất cả</option>
                    @foreach (var item in Model.LstGroup)
                    {
                        <option value="@item.GroupId">@item.GroupName </option>
                    }
                </select>    
            </div>
            <div class="show-message"></div>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-6">
            <label class="control-label" for="txtSMSTitle">Nội dung SMS <span style="color:Red;">*</span></label>
            <div class="input-group">
                <textarea id="txtSMSTitle"  class="form-control text-input"  cols="4" rows="6"></textarea>
            </div>
            <div class="show-message"></div>
        </div>
        <div class="form-group col-md-6">
            <label class="control-label" for="txtDescription">Mô tả</label>
            <div class="input-group">
                <textarea id="txtDescription"  class="form-control text-input"  cols="4" rows="6"></textarea>    
            </div>
            <div class="show-message"></div>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-md-12" style="padding-right:0px;" >
            <label class="control-label" for="chkIsHasSession">Chia phiên tham dự (Có / không)</label>
            <div class='input-group' >
                <input type="checkbox" id="chkIsHasSession" class="checkbox" />
            </div>
            <div class="show-message"></div>
        </div>
    </div>
    @Html.Partial("~/Views/Session/CreatePartial.cshtml")
    <hr />
    <div class="actions row">
        <button id="btnSave" type="button" class="btn btn-primary"><i class="icon-save"></i>&nbsp;Lưu</button>
        <button id="btnCancel" type="button" class="btn btn-primary"><i class="icon-refresh"></i>&nbsp;Reset</button>
        <button id="btnClose" type="button" class="btn btn-primary"><i class="icon-close"></i>&nbsp;Đóng</button>
    </div>
</div>

Views/Event/Index.cshtml
@using BCRM.CheckInEvent.Models
@model EventIndexSearchModel
@{
    Layout = "~/Views/Shared/_ContentLayout.cshtml";
    var currentUsser = (UserModel)ViewBag.CurrentUser;
}
<h1 style="padding-left: 15px;">
    Quản lý sự kiện</h1>
<div class="panel panel-search"  id="frmSearchEvent">
    <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Tìm kiếm thông tin sự kiện</div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-4">
                <div class="input-group">
                    <input type="text" id="txtSearchText" class="form-control" id="txtSearchText" placeholder="-- Tên sự kiện --" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="input-group">
                    <select id="ddlDeployEvent" class="chzn-select form-control select" placeholder="Lựa chọn phòng ban" >
                        <option value="0">Chọn tất cả</option>
                        @foreach (var item in Model.LstGroup)
                        {
                            <option value="@item.GroupId">@item.GroupName </option>
                        }
                    </select>
                </div>
            </div>
            <div class="col-md-2">
                <div class='input-group date' >
                    <input type='text' id='txtStartDate' value= "" placeholder="-- Ngày bắt đầu --" class="form-control" />
                </div>
            </div>
            <div class="col-md-2">
                <div class='input-group date' >
                    <input type='text' id='txtEndDate' placeholder="-- Ngày kết thúc --" class="form-control" />
                </div>
            </div>
        </div>
        <div style="width: 100%;margin-top:3px; margin-bottom: 3px;">
            <button id="btnSearch" class="btn btn-success" type="button"><i class="icon-search"></i>&nbsp;Tìm kiếm</button>
            <button id="btnAddNew" class="btn btn-success" type="button"><i class="icon-plus"></i>&nbsp;Tạo mới</button>
        </div>
    </div>
</div>
<div class="panel panel-result"  id="SearchEvent">
    <div class="panel-heading"><i class="icon-reorder"></i> &nbsp; Danh sách sự kiện</div>
    <div class="panel-body">
        
    </div>
</div>
<div class="panel panel-action"  id="CreateEvent">
    <div class="panel-heading"><i class="icon-reorder"></i>&nbsp; Thêm mới sự kiện</div>
    <div class="panel-body">
        @Html.Action("Create", "Event")
    </div>
</div>

<div class="panel panel-action hide"  id="EditEvent">
    <div class="panel-heading"><i class="icon-reorder"></i>&nbsp; Sửa sự kiện</div>
    <div class="panel-body">
    </div>
</div>
<div id="ShowSlotRotate" class="create-event hide"  style="width: 100%;margin-top:15px; padding-left:15px;">
</div>
<script type="text/javascript">
    event_index.init();
</script>

Views/Event/Search.cshtml
@using BCRM.CheckInEvent.Models
@using Libs
@model EventIndexSearchModel
@{
    Layout = null;
    var pager = (PagerModel)ViewBag.Pager;
    pager.ActionScript = "event_index.search";
    var count = 0;
}
<table id="tablInviteEvent" class="table-striped table-bordered" style="width: 100%">
    <thead>
        <tr>
            <th>STT</th>
            <th>Mã sự kiện</th>
            <th>Tên sự kiện</th>
            <th>Ngày bắt đầu</th>
            <th>Ngày kết thúc</th>
            <th>Cài đặt mặc định</th>
            <th>Trạng thái </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LstEvent)
        {
            count++;
             <tr>
                <td>@count</td>
                <td>@item.EventCode</td>
                <td>@item.Name</td>
                <td>@item.StartDate.ToString("dd/MM/yyyy")</td>
                <td>@item.EndDate.ToString("dd/MM/yyyy")</td>
                <td>
                    @if (item.IsDefaultEvent)
                    {
                         <span class="label label-success">Mặc định</span>  
                    }
                 </td>
                <td>
                    @if (item.IsEnable == true)
                    {
                        <span class="label label-success">Hoạt động</span>  
                    }
                    else
                    {
                        <span class="label  label-danger">Đang dừng</span>
                    }
                </td>
                <td>
                    <div class="dropdown">
                      <button class="btn btn-primary small dropdown-toggle" style="font-size:11px !important;line-height:13px;padding:4px 10px;" type="button" data-toggle="dropdown">
                      <i class="icon-cog"></i>&nbsp;Quản lý
                      <span class="caret"></span></button>
                      <ul class="dropdown-menu">
                            @if (item.IsInWebCheckIn)
                            {
                                <li>
                                    <a name="btnEdit" uid ="@item.Id"  href="javascript:void(0);"><i class="icon-edit"></i>&nbsp;Sửa</a>
                                </li>
                                if (item.IsEnable == true)
                                {
                                    <li>
                                        <a name="btnStop" uid ="@item.Id"  href="javascript:void(0);"><i class="icon-stop"></i>&nbsp;Dừng hoạt động</a>
                                    </li>     
                                }
                                else
                                {
                                     <li>
                                        <a name="btnActive" uid ="@item.Id"  href="javascript:void(0);"><i class="icon-ok"></i>&nbsp;Chạy sự kiện</a>
                                    </li>
                                }
                            }
                            @if (item.IsEnable && !item.IsDefaultEvent )
                            {
                                <li>
                                    <a name="btnSetDefault" uid ="@item.Id" iwci="@(item.IsInWebCheckIn ? 1 : 0)"  href="javascript:void(0);"><i class="icon-ok"></i>&nbsp;Sự kiện mặc định</a>
                                </li>
                            }
                            <li>
                                <a name="btnSlot" target="_blank" href="@("/quay-so-trung-thuong/" + item.Id + "/" + (item.IsInWebCheckIn == true ? 1 : 0))" ><i class="icon-gift"></i>&nbsp;Quay số trúng thưởng </a>
                            </li>
                            <li>
                                <a name="btnListLuckyNumber" uid="@item.Id" iwci="@(item.IsInWebCheckIn ? 1 : 0)"  href="javascript:void(0);" ><i class="icon-gift"></i>&nbsp;Danh sách trúng thưởng </a>
                            </li>
                      </ul>
                    </div>
                </td>
             </tr>
        }
    </tbody>
</table>
@Html.Action("Paging", "Common", new { pager = ViewBag.Pager })