Controllers/InviteEventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BCRM.CheckInEvent.Models;
using BCRM.CheckInEvent.DAL;
using Libs;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using Newtonsoft.Json;
using DVS.Algorithm;
using System.Web.Configuration;
using BCRM.CheckInEvent.Common;
using System.Text;

namespace BCRM.CheckInEvent.Controllers
{
    public class InviteEventController : BaseController
    {
        #region Methods
        [FilterAuthorize]
        public ActionResult Index()
        {
            ViewBag.CurrentUser = UserContext;
            var eventDL = new EventDL();
            // Lấy danh sách các sự kiện
            var lstAllEvents = CommonMethod.GetEvents();
            var defaultEvent = CommonMethod.GetDefaultEvent();
            ViewBag.DefaultEvent = defaultEvent;
            return View(lstAllEvents);
        }
        [FilterAuthorize]
        public ActionResult Search(EventIndexModel model)
        {
            //if (model.TextSearch == null)
            //{
            //    model.TextSearch = string.Empty;
            //}
            //if (!string.IsNullOrEmpty(model.TextSearch))
            //{
            //    model.TextSearch = model.TextSearch.Trim();
            //}

            //if (model.InviteeCode == null)
            //{
            //    model.InviteeCode = string.Empty;
            //}
            //var result = new EventIndexModel();
            //// Thông tin tìm kiếm theo BCRM
            //if (!model.IsInWebCheckin)
            //{
            //}
            //// Thông tin tìm kiếm theo WebCheckin
            //else
            //{
            //    var inviteEventDL = new InviteEventDL();
            //    // Tìm kiếm theo id của khách mời
            //    if (model.InviteeCodeInWebCheckin > 0)
            //    {
            //        var lstSearchResult = new List<InviteEventModel>();
            //        var info = inviteEventDL.WebCheckIn_GetById(model.InviteeCodeInWebCheckin);
            //        if (info != null && info.Status == true)
            //        {
            //            lstSearchResult.Add(info);
            //        }

            //        result.LstInviteEvents = lstSearchResult;
            //        result.PageIndex = model.PageIndex;
            //        result.PageSize = model.PageSize;
            //        result.TotalRecord = lstSearchResult.Count;
            //    }
            //    else if (!string.IsNullOrEmpty(model.Code))
            //    {
            //        // TH người dùng tìm kiếm theo mã số khách mời
            //        int searchByCode = 0;
            //        if (int.TryParse(model.Code, out searchByCode))
            //        {
            //            var eventDataLayer = new EventDL();
            //            var evtInfo = eventDataLayer.GetByIdInWebCheckIn(model.EventId);
            //            if (evtInfo != null)
            //            {
            //                model.Code = evtInfo.EventCode + model.Code;
            //            }
            //        }

            //        // Lấy danh sách khách khách mời chính theo mã code
            //        var lstInviteEvent = inviteEventDL.WebCheckin_GetByCodeToCheckin(model.EventId, model.Code);
            //        // paging
            //        result.LstInviteEvents = lstInviteEvent.OrderBy(o => o.Code)
            //                                                .Skip(model.PageSize * (model.PageIndex - 1))
            //                                                .Take(model.PageSize).ToList();
            //        result.TotalRecord = lstInviteEvent.Count;
            //        result.PageSize = model.PageSize;
            //        result.PageIndex = model.PageIndex;
            //    }
            //    else
            //    {
            //        if (model.CustomerType == null)
            //        {
            //            model.IsNotSuggest = null;
            //        }
            //        else
            //        {
            //            if (model.CustomerType == 0)
            //            {
            //                model.IsNotSuggest = false;
            //            }
            //            else
            //            {
            //                model.IsNotSuggest = true;
            //            }
            //        }
            //        var lstSearchResult = inviteEventDL.WebCheckIn_GetByCondition(model);
            //        // Tìm kiếm theo thông tin
            //        // find invitee 
            //        if (!string.IsNullOrEmpty(model.TextSearch))
            //        {
            //            var convertUnsign = CommonMethod.ConvertToUnSign(model.TextSearch.ToLower());
            //            var exactMatchInvitee = lstSearchResult.FindAll(o => o.CustomerName.ToLower().Contains(model.TextSearch.ToLower()) || o.CustomerPhone.ToLower().Contains(model.TextSearch.ToLower()));
            //            var opportunityInvitee = lstSearchResult.FindAll(o =>
            //                                                    !o.CustomerName.ToLower().Contains(model.TextSearch.ToLower())
            //                                                    && !o.CustomerPhone.ToLower().Contains(model.TextSearch.ToLower())
            //                                                    && (CommonMethod.ConvertToUnSign(o.CustomerName.ToLower()).Contains(convertUnsign) || o.CustomerEmail.Contains(convertUnsign))
            //                                                    );
            //            var remainInvitee = lstSearchResult.FindAll(o => !o.CustomerName.ToLower().Contains(model.TextSearch.ToLower())
            //                                                            && !o.CustomerPhone.ToLower().Contains(model.TextSearch.ToLower())
            //                                                            && !CommonMethod.ConvertToUnSign(o.CustomerName.ToLower()).Contains(convertUnsign)
            //                                                            && !o.CustomerEmail.Contains(convertUnsign)
            //                                                            && ((o.CompanyName != null && CommonMethod.ConvertToUnSign(o.CompanyName.ToLower()).Contains(convertUnsign))
            //                                                             || (o.PositionName != null && CommonMethod.ConvertToUnSign(o.PositionName.ToLower()).Contains(convertUnsign))
            //                                                             || (o.PlaceOfAttendEvent != null && CommonMethod.ConvertToUnSign(o.PlaceOfAttendEvent.ToLower()).Contains(convertUnsign))
            //                                                             || (o.Note != null && CommonMethod.ConvertToUnSign(o.Note.ToLower()).Contains(convertUnsign))
            //                                                                )
            //                                                            );
            //            var lstAllInvitee = new List<InviteEventModel>();
            //            lstAllInvitee.AddRange(exactMatchInvitee);
            //            lstAllInvitee.AddRange(opportunityInvitee);
            //            lstAllInvitee.AddRange(remainInvitee);
            //            result.LstInviteEvents = lstAllInvitee.Skip(model.PageSize * (model.PageIndex - 1))
            //                                           .Take(model.PageSize).ToList();
            //            result.PageIndex = model.PageIndex;
            //            result.PageSize = model.PageSize;
            //            result.TotalRecord = lstAllInvitee.Count;
            //        }
            //        else
            //        {
            //            result.LstInviteEvents = lstSearchResult.OrderByDescending(o => o.CreatedDate)
            //                                            .Skip(model.PageSize * (model.PageIndex - 1))
            //                                            .Take(model.PageSize).ToList();
            //            result.PageIndex = model.PageIndex;
            //            result.PageSize = model.PageSize;
            //            result.TotalRecord = lstSearchResult.Count;
            //        }

            //    }
            //}
            //var eventDL = new EventDL();
            //var sessionDL = new SessionDL();
            //var sessionCheckinDL = new SessionCheckinDL();
            //#region Lấy thông tin checkin
            //var lstSession = sessionDL.GetByEventId(model.EventId);
            //if (lstSession.Count > 0)
            //{
            //    foreach (var item in result.LstInviteEvents)
            //    {
            //        item.IsUsingSession = true;
            //        var lstCheckin = sessionCheckinDL.GetByInviteEventId(item.Id);
            //        var lstSelectedSessionId = new List<string>();
            //        if (!string.IsNullOrEmpty(item.Sessions))
            //        {
            //            lstSelectedSessionId = item.Sessions.Split(',').ToList();
            //        }
                    
            //        item.LstSessionCheckin = new List<KeyValuePair<string, string>>();
            //        if (lstSelectedSessionId.Contains("0"))
            //        {
            //            foreach (var sessionItem in lstSession)
            //            {
            //                var ifo = lstCheckin.Find(o => o.SessionId == sessionItem.Id);
            //                if (ifo == null)
            //                {
            //                    item.LstSessionCheckin.Add(new KeyValuePair<string, string>(sessionItem.Name, "<span class=\"label  label-danger\">Chưa check in</span>"));
            //                }
            //                else
            //                {

Views/InviteEvent/AccompanyInvitee.cshtml
@using BCRM.CheckInEvent.Models
@model CheckInInfo
@{
    Layout = null;
}
<div id="frmAddAccompanyInvitee" style="width: 420px; display: block; top: 40%; left: 40%; height: 228px; overflow-x: hidden; overflow-y: hidden !important;"  class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialogSuccessLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="height: 100%;padding: 0px;border: none;">
        <div class="modal-content" style="border-radius:0px;width: 420px;">
            <div class="modal-header" style="color: #fff;background-color: #428bca;border-color: #d43f3a;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="dialogSuccessLabel">Khách đi cùng</h4>
            </div>
            <div class="modal-body"  style="margin-bottom:15px;">
                <div class="row" >
                    <div class="form-group col-md-12">
                        <label for="txtAccompanyInvitee">Số lượng khách đi cùng <span style="color:Red;">*</span></label>
                        <input type='text' id='txtAccompanyInvitee' value="@Model.AccompanyInvitee" class="form-control" />
                    </div>
                </div>
                <div class="actions col-md-12" style="margin-bottom:15px;">
                    <input type="hidden" id="hdfEventId" value="@Model.EventId" />
                    <input type="hidden" id="hdfInviteEventId" value="@Model.InviteEventId" />
                    <input type="hidden" id="hdfAttachId" value="@Model.AttachId" />
                    <button id="btnSave" type="button" class="btn btn-primary"><i class="icon-save"></i>&nbsp;Lưu</button>
                    <button id="btnCancel" type="button" class="btn btn-primary"  data-dismiss="modal"><i class="icon-remove"></i>&nbsp;Hủy</button>
                </div> 
            </div>
        </div>
    </div>
</div>

Views/InviteEvent/AccompanyInviteeInWebChecin.cshtml
@using BCRM.CheckInEvent.Models
@model CheckInInfo
@{
    Layout = null;
}
<div id="frmAddAccompanyInviteeInWebCheckin"  style="width: 420px; display: block; top: 25%; left: 40%; overflow-x: hidden; overflow-y: hidden !important;outline:none;"  class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialogSuccessLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="height: 100%;padding: 0px;border: none;">
        <div class="modal-content" style="border-radius:0px;width: 420px;">
            <div class="modal-header" style="color: #fff;background-color: #428bca;border-color: #d43f3a;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="dialogSuccessLabel">Thông tin checkin</h4>
            </div>
            <div class="modal-body">
                @if (Model.IsHasSession)
                {
                     <div class="row">
                        <div class="form-group col-md-12">
                            <label class="control-label" for="dllSessionId">Chọn phiên <span style="color:Red;">*</span></label>
                            <div class="control-label">
                                <select id="dllSessionId" class="form-control select">
                                    @foreach (var session in Model.LstSession)
                                    {
                                        if (Model.SessionId == session.Id)
                                        {
                                            <option selected="selected" value="@session.Id"> @session.Name</option> 
                                        }
                                        else
                                        {
                                            <option value="@session.Id"> @session.Name</option>      
                                        }

                                    }
                                </select>
                            </div>
                            <div class="show-message"></div>
                        </div>
                    </div>
                }
                
                <div class="row">
                    <div class="form-group col-md-12">
                        <label class="control-label" for="txtAccompanyInvitee">Số lượng khách đi cùng <span style="color:Red;">*</span></label>
                        <div class="control-label">
                            <input type='number' id='txtAccompanyInvitee' value="@Model.AccompanyInvitee" class="form-control phone-search text-input" />
                        </div>
                        <div class="show-message"></div>
                    </div>
                </div>
                <hr />
                <div class="actions col-md-12" style="margin-bottom:15px;">
                    <input type="hidden" id="hdfEventId" value="@Model.EventId" />
                    <input type="hidden" id="hdfInviteEventId" value="@Model.InviteEventId" />
                    <button id="btnSave" type="button" class="btn btn-success"><i class="icon-save"></i>&nbsp;XÁC NHẬN</button>
                    <button id="btnCancel" type="button" class="btn btn-primary"  data-dismiss="modal"><i class="icon-remove"></i>&nbsp;Hủy</button>
                </div> 
            </div>
        </div>
    </div>
</div>

Views/InviteEvent/AddAccompanyMemberWebCheckin.cshtml
@using BCRM.CheckInEvent.Models
@model CheckInInfo
@{
    Layout = null;
}
<div id="frmJustAddAccompanyMemberInWebCheckin" style="margin-top:25px;">
    <div class="row"  style="margin-left:0;">
        <div class="form-group col-md-4">
            <label for="txtAccompanyInvitee">Số lượng khách đi cùng <span style="color:Red;">*</span></label>
            <input type='number' id='txtAccompanyInvitee' value="@Model.AccompanyInvitee" class="form-control phone-search" />
        </div>
    </div>
    <div class="actions col-md-12" style="margin-bottom:15px;">
        <input type="hidden" id="hdfEventId" value="@Model.EventId" />
        <input type="hidden" id="hdfInviteEventId" value="@Model.InviteEventId" />
        <button id="btnSave" type="button" class="btn btn-primary"><i class="icon-save"></i>&nbsp;Lưu</button>
        <button id="btnCancel" type="button" class="btn btn-primary"><i class="icon-remove"></i>&nbsp;Hủy</button>
    </div>    
</div>

<script type="text/javascript">
    accompany_member_add.init();
</script>

Views/InviteEvent/AddQuantityAccompanyInvitee.cshtml
@using BCRM.CheckInEvent.Models
@model CheckInInfo
@{
    Layout = null;
}
<div id="frmAddQuantityAccompanyInvitee" style="margin-top:25px;">
    <div class="row"  style="margin-left:0;">
        <div class="form-group col-md-4">
            <label for="txtAccompanyInvitee">Số lượng khách đi cùng <span style="color:Red;">*</span></label>
            <input type='text' id='txtAccompanyInvitee' value="@Model.AccompanyInvitee" class="form-control" />
        </div>
    </div>
    <div class="actions col-md-12" style="margin-bottom:15px;">
        <input type="hidden" id="hdfEventId" value="@Model.EventId" />
        <input type="hidden" id="hdfInviteEventId" value="@Model.InviteEventId" />
        <input type="hidden" id="hdfAttachId" value="@Model.AttachId" />
        <button id="btnSave" type="button" class="btn btn-primary"><i class="icon-save"></i>&nbsp;Lưu</button>
        <button id="btnCancel" type="button" class="btn btn-primary"><i class="icon-remove"></i>&nbsp;Hủy</button>
    </div>    
</div>
<script type="text/javascript">
    add_accompany_invitee_bcrm.init();
</script>

Views/InviteEvent/ChangeSession.cshtml
@using BCRM.CheckInEvent.Models
@model InviteEventSessionChangeModel
@{
    Layout = null;
}
<div id="frmChangeSession"  style="width: 420px; display: block; top: 25%; left: 40%; overflow-x: hidden; overflow-y: hidden !important;outline:none;"  class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialogSuccessLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="height: 100%;padding: 0px;border: none;">
        <div class="modal-content" style="border-radius:0px;width: 420px;">
            <div class="modal-header" style="color: #fff;background-color: #428bca;border-color: #d43f3a;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="dialogSuccessLabel">Thay đổi phiên tham dự</h4>
            </div>
            <div class="modal-body">
                 <div class="row">
                    <div class="form-group col-md-12">
                        <label class="control-label" for="dllSessions">Chọn phiên <span style="color:Red;">*</span></label>
                        <div class="control-label">
                            <select id="dllSessions" multiple class="chzn-select form-control select">
                                @foreach (var session in Model.LstSession)
                                {
                                    if (Model.LstSelectedSessionId.Contains(session.Id.ToString()))
                                    {
                                        <option selected="selected" value="@session.Id"> @session.Name</option>      
                                    }
                                    else
                                    {
                                        <option value="@session.Id"> @session.Name</option> 
                                    }
                                }
                            </select>
                        </div>
                        <div class="show-message"></div>
                    </div>
                </div>
                <hr />
                <div class="actions col-md-12" style="margin-bottom:15px;">
                    <input type="hidden" id="hdfEventId" value="@Model.EventId" />
                    <input type="hidden" id="hdfInviteEventId" value="@Model.InviteEventId" />
                    <input type="hidden" id="hdfCheckedinSessionId" value="@Model.CheckedinSessionId" />
                    <button id="btnSaveChangeSession" type="button" class="btn btn-success"><i class="icon-save"></i>&nbsp;XÁC NHẬN</button>
                    <button id="btnCancelChangeSession" type="button" class="btn btn-primary"  data-dismiss="modal"><i class="icon-remove"></i>&nbsp;Hủy</button>
                </div> 
            </div>
        </div>
    </div>
</div>

Views/InviteEvent/CheckinDetail.cshtml
@using BCRM.CheckInEvent.Models
@model SessionCheckinInfo
@{
    Layout = null;
    var count = 0;
}
<div id="frmCheckinDetail"  style="width: 820px; display: inline-table; top: 25%; left: 20%; overflow-x: hidden; overflow-y: hidden !important;outline:none;"  class="modal fade" tabindex="-1" role="dialog" aria-labelledby="dialogSuccessLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="height: 100%;padding: 0px;border: none;display:table-cell; ">
        <div class="modal-content" style="border-radius:0px;width: 820px;">
            <div class="modal-header" style="color: #fff;background-color: #428bca;border-color: #d43f3a;">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="dialogSuccessLabel">Chi tiết checkin</h4>
            </div>
            <div class="modal-body">
                 <div class="row">
                    <table class="table-striped table-bordered" style="width: 100%">
                        <thead>
                            <tr>
                                <th style="width: 60px;text-align:center; ">#</th>
                                @if (Model.IsHasSession)
                                {
                                    <th>Tên phiên</th>     
                                }
                                <th style="width: 150px">Người checkin</th>
                                <th style="width: 200px">Thời gian checkin</th>
                                <th style="width: 200px">Số khách đi cùng</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.LstDetail)
                            {
                                count++;
                                <tr style="height:30px;" >
                                    <td style="text-align:center;" >@count</td>
                                    @if (Model.IsHasSession)
                                    {
                                        <td style="padding-left:5px;">@item.SessionName</td>     
                                    }
                                    <td style="padding-left:5px;">@item.CheckinBy</td>
                                    <td style="padding-left:5px;">@item.CheckinDate.ToString("dd/MM/yyyy HH:mm:ss")</td>
                                    <td style="text-align:center;" >@item.AccompanyMember </td>
                                </tr> 
                            }
                        </tbody>
                    </table>
                </div>
                <hr />
                <div class="actions col-md-12" style="margin-bottom:15px;">
                    <button id="btnCancelCheckinDetail" type="button" class="btn btn-primary"  data-dismiss="modal"><i class="icon-remove"></i>&nbsp;Đóng</button>
                </div> 
            </div>
        </div>
    </div>
</div>

Views/InviteEvent/Index.cshtml
@using BCRM.CheckInEvent.Models
@model List<EventModel>
@{
    Layout = "~/Views/Shared/_ContentLayout.cshtml";
    var currentUsser = (UserModel)ViewBag.CurrentUser;
    var defaultEvent = ViewBag.DefaultEvent == null ? new EventModel(){Id=0} : (EventModel)ViewBag.DefaultEvent;
}
<style type="text/css">
    input.phone-search::-webkit-outer-spin-button,
    input.phone-search::-webkit-inner-spin-button 
    {
        -webkit-appearance: none;
        margin: 0;
    }
    input.phone-search {
        -moz-appearance:textfield;
    }
</style>
<h1 style="padding-left: 15px;">Quản lý checkin</h1>
@using (Html.BeginForm("ExportExcel", "InviteEvent", FormMethod.Post, new { id = "inviteEventForm" , target="_blank" }))
{
    <div class="panel panel-search"  id="frmSearchInviteEvent">
        <div class="panel-heading"><i class="icon-cogs"></i> &nbsp; Tìm kiếm thông tin khách mời</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3">
                    <textarea name="TextSearch" rows="3" cols="5" tabindex="1" class="form-control" id="txtSearchText" placeholder="Tìm kiếm theo họ tên, email,điện thoại ... "></textarea>
                </div>
                <div class="col-md-9">
                    <div class="row">
                        <div class="col-md-5">
                            <select name="EventIdWebCheckIn" id="selEvent" class="form-control" title="Danh sách các sự kiện diễn ra">
                                @foreach (var e in Model)
                                {
                                    if (e.Id == defaultEvent.Id && e.IsInWebCheckIn == defaultEvent.IsInWebCheckIn)
                                    {
                                        <option selected="selected" value="@(e.Id + "_" + (e.IsInWebCheckIn == true ? "1" : "0"))">@e.Name</option>                                               
                                    }
                                    else
                                    {
                                        <option value="@(e.Id + "_" + (e.IsInWebCheckIn == true ? "1" : "0"))">@e.Name</option> 
                                    }
                                }
                            </select>        
                        </div>       
                        <div class="col-md-3">
                            <select name="SessionId" id="selSessionId" class="form-control" title="Lựa chọn phiên tham dự"></select>
                        </div>
                        <div class="col-md-4">
                            <select name="CheckInStatus" tabindex="4" id="selIsCheckIn" class="form-control" title="Thông tin khách đã check in hay chưa">
                                <option value="">--Tất cả trạng thái--</option>
                                <option value="0">Chưa CheckIn</option>
                                <option value="1">Đã CheckIn</option>
                            </select>        
                        </div>   
                    </div>
                    <div class="row" style="margin-top:3px;">
                        <div class="col-md-3">
                            <input type="text" tabindex="2" name="InviteeCode" id="txtInviteeCode" placeholder="- Mã khách mời -" class="form-control" />
                        </div>
                        <div class="col-md-3 hide">
                            <input type="number" tabindex="2" name="InviteeCodeInWebCheckin" id="txtInviteeCodeInWebCheckin" placeholder="- Mã khách mời -" class="form-control phone-search" />
                        </div>
                        <div class="col-md-2">
                            <input type="text" tabindex="3" name="Code" id="txtCode" placeholder="- Mã vé -" class="form-control" />
                        </div>
                        <div class="col-md-3">
                            <select name="ImportanceLevel" tabindex="5" id="selImportantanceLevel" class="form-control" title="Mức độ quan trọng">
                                <option value="">- Mức độ quan trọng -</option>
                                <option value="0">Khách thường</option>
                                <option value="1">Khách VIP</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <select name="CustomerType" tabindex="5" id="selCustomerType" class="form-control" title="Loại khách">
                                <option value="">- Lựa chọn loại khách -</option>
                                <option value="0">Khách chính</option>
                                <option value="1">Khách đính kèm</option>
                                <option value="2">Khách vãng lai</option>
                            </select>
                        </div> 
                    </div>    
                </div>
            </div>
            <div style="width: 100%;margin-top:3px; margin-bottom: 3px;">
                <button id="btnSearch" class="btn btn-success" type="button">
                    <i class="icon-search"></i>&nbsp;Tìm kiếm</button>
                @if (currentUsser.HasPermisson(BCRM.CheckInEvent.Common.Permission.Manager) ||
                     currentUsser.HasPermisson(BCRM.CheckInEvent.Common.Permission.Admin))
                {
                    <button id="btnExport" class="btn btn-success" type="submit">
                        <i class="icon-refresh"></i>&nbsp;Xuất Excel</button>    
                }
                <button id="btnAddAnonymous" class="btn btn-success" type="button"><i class="icon-plus"></i>&nbsp;Khách vãng lai</button>
            </div>
        </div>
    </div>
}

<div class="panel panel-result" id="SearchInviteEvent">
    <div class="panel-heading"><i class="icon-reorder"></i> &nbsp; Danh sách khách mời checkin</div>
    <div class="panel-body">
        
    </div>
</div>
<div class="panel panel-action hide" id="AddAnonymousInfo">
    <div class="panel-heading"><i class="icon-reorder"></i> &nbsp; Thêm thông tin khách vãng lai</div>
    <div class="panel-body">
        
    </div>
</div>
<div class="panel panel-action hide" id="AccompanyInvitee">
    <div class="panel-heading"><i class="icon-reorder"></i> &nbsp; Thêm số lượng khách đi cùng</div>
    <div class="panel-body">
        
    </div>
</div>
<div id="AddInvitee" class="hide">
    <div class="info">
        @Html.Action("Create", "InviteEvent")
    </div>
</div>
<div class="panel panel-action hide" id="EditInviteeInWebCheckin">
    <div class="panel-heading"><i class="icon-reorder"></i> &nbsp; Sửa thông tin khách mời</div>
    <div class="panel-body">
        
    </div>
</div>
<div id="divAddCheckinNum" >
    <div class="info"></div>
</div>
<div id="wrapChangeSession">
    
</div>
<div id="wrapCheckinDetail">

</div>
<script type="text/javascript">
    invite_event_index.init();
</script>